version: '3.8'
services:
  backend:
    build:
      context: ./store-backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes: 
      - ./store-backend:/app
    restart: always

  frontend:
    build:
      context: ./store-frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend
    restart: always
